// Generated by CoffeeScript 1.7.1
var async, expect, request, _;

request = require("superagent");

expect = require("expect.js");

async = require("async");

_ = require("lodash");

describe("Server", function() {
  return it("responds to basic requests", function(done) {
    return request.get("localhost:3000/").end(function(res) {
      expect(res).to.exist;
      expect(res.status).to.equal(200);
      return done();
    });
  });
});

describe("API", function() {
  describe("surnames", function() {
    it("responds to /api/surnames", function(done) {
      return request.get("localhost:3000/api/surnames").end(function(res) {
        expect(res).to.exist;
        expect(res.status).to.equal(200);
        return done();
      });
    });
    it("returns a JSON array of 10 names by default", function(done) {
      return request.get("localhost:3000/api/surnames").end(function(res) {
        expect(res.body).to.exist;
        expect(res.body).to.not.be.empty();
        expect(res.body).to.have.key("surnames");
        expect(res.body.surnames).to.be.an(Array);
        expect(res.body.surnames).to.have.length(10);
        return done();
      });
    });
    describe("the limit query", function() {
      it("changes the number of results", function(done) {
        return request.get("localhost:3000/api/surnames?limit=23").end(function(res) {
          expect(res.body).to.exist;
          expect(res.body.surnames).to.have.length(23);
          return done();
        });
      });
      return it("returns 10 results if the limit is over 100 or under 0", function(done) {
        return request.get("localhost:3000/api/surnames?limit=130").end(function(res) {
          expect(res.body.surnames).to.have.length(10);
          return done();
        });
      });
    });
    describe("the frequency query", function() {
      it("low returns names with frequencies below 0.1", function(done) {
        return request.get("localhost:3000/api/surnames?frequency=low").end(function(res) {
          async.each(res.body.surnames, function(name) {
            return expect(name.frequency).to.be.lessThan(0.1);
          });
          return done();
        });
      });
      it("medium returns names with frequencies >= 0.06 and < 1", function(done) {
        return request.get("localhost:3000/api/surnames?frequency=medium").end(function(res) {
          async.each(res.body.surnames, function(name) {
            expect(name.frequency).to.be.greaterThan(0.059);
            return expect(name.frequency).to.be.lessThan(1);
          });
          return done();
        });
      });
      return it("high returns names with frequencies >=1", function(done) {
        return request.get("localhost:3000/api/surnames?frequency=high").end(function(res) {
          async.each(res.body.surnames, function(name) {
            return expect(name.frequency).to.be.greaterThan(0.99);
          });
          return done();
        });
      });
    });
    return describe("the racial query", function() {
      it("returns names with pctblack above 50 when sent pctblack, 50", function(done) {
        return request.get("localhost:3000/api/surnames?race=pctblack&race=50").end(function(res) {
          async.each(res.body.surnames, function(name) {
            return expect(name.pctblack).to.be.greaterThan(50);
          });
          return done();
        });
      });
      it("returns names with pctasian above 20 when sent pctasian, 20", function(done) {
        return request.get("localhost:3000/api/surnames?race=pctasian&race=20").end(function(res) {
          async.each(res.body.surnames, function(name) {
            return expect(name.pctasian).to.be.greaterThan(20);
          });
          return done();
        });
      });
      it("returns names with pctnative above 60 when sent pctnative, 60", function(done) {
        return request.get("localhost:3000/api/surnames?race=pctnative&race=60").end(function(res) {
          async.each(res.body.surnames, function(name) {
            return expect(name.pctnative).to.be.greaterThan(60);
          });
          return done();
        });
      });
      it("returns names with pctwhite above 90 when sent pctwhite, 90", function(done) {
        return request.get("localhost:3000/api/surnames?race=pctwhite&race=90").end(function(res) {
          async.each(res.body.surnames, function(name) {
            return expect(name.pctwhite).to.be.greaterThan(90);
          });
          return done();
        });
      });
      it("returns names with pcthispanic above 95 when sent pcthispanic, 95", function(done) {
        return request.get("localhost:3000/api/surnames?race=pcthispanic&race=95").end(function(res) {
          async.each(res.body.surnames, function(name) {
            return expect(name.pcthispanic).to.be.greaterThan(95);
          });
          return done();
        });
      });
      it("returns results when sent a non-existent race", function(done) {
        return request.get("localhost:3000/api/surnames?race=pctdog&race=95").end(function(res) {
          expect(res.body).to.exist;
          return done();
        });
      });
      return it("returns results when sent a wrong race number", function(done) {
        return request.get("localhost:3000/api/surnames?race=pctwhite&race=dog").end(function(res) {
          expect(res.body).to.exist;
          return done();
        });
      });
    });
  });
  return describe("firstnames", function() {
    it("responds to /api/firstnames", function(done) {
      return request.get("localhost:3000/api/firstnames").end(function(res) {
        expect(res).to.exist;
        expect(res.status).to.equal(200);
        return done();
      });
    });
    it("returns a JSON array of 10 names by default", function(done) {
      return request.get("localhost:3000/api/firstnames").end(function(res) {
        expect(res.body).to.exist;
        expect(res.body).to.not.be.empty();
        expect(res.body).to.have.key("firstnames");
        expect(res.body.firstnames).to.be.an(Array);
        expect(res.body.firstnames).to.have.length(10);
        return done();
      });
    });
    describe("the year query", function() {
      it("returns names from 1985 if set year=1985", function(done) {
        return request.get("localhost:3000/api/firstnames?year=1985").end(function(res) {
          async.each(res.body.firstnames, function(name) {
            return expect(name.year).to.eql(1985);
          });
          return done();
        });
      });
      return it("returns results from year 0 if year is gibberish", function(done) {
        return request.get("localhost:3000/api/firstnames?year=boogie").end(function(res) {
          async.each(res.body.firstnames, function(name) {
            return expect(name.year).to.eql(0);
          });
          return done();
        });
      });
    });
    describe("the limit query", function() {
      it("changes the number of results", function(done) {
        return request.get("localhost:3000/api/firstnames?limit=33").end(function(res) {
          expect(res.body).to.exist;
          expect(res.body.firstnames).to.have.length(33);
          return done();
        });
      });
      return it("returns 10 results if the limit is over 100 or under 0", function(done) {
        return request.get("localhost:3000/api/firstnames?limit=229").end(function(res) {
          expect(res.body.firstnames).to.have.length(10);
          return done();
        });
      });
    });
    return describe("the gender query", function() {
      it("returns a mix of male and female names when left blank", function(done) {
        return request.get("localhost:3000/api/firstnames?limit=20").end(function(res) {
          var genders;
          genders = [];
          _(res.body.firstnames).forEach(function(name) {
            return genders.push(name.gender);
          });
          genders = _.uniq(genders);
          expect(genders).to.contain("M");
          expect(genders).to.contain("F");
          return done();
        });
      });
      it("returns only male names when sent gender=male", function(done) {
        return request.get("localhost:3000/api/firstnames?gender=male").end(function(res) {
          async.each(res.body.firstnames, function(name) {
            return expect(name.gender).to.eql("M");
          });
          return done();
        });
      });
      it("returns only female names when sent gender=female", function(done) {
        return request.get("localhost:3000/api/firstnames?gender=female").end(function(res) {
          async.each(res.body.firstnames, function(name) {
            return expect(name.gender).to.eql("F");
          });
          return done();
        });
      });
      return it("returns results when gender is set to gibberish", function(done) {
        return request.get("localhost:3000/api/firstnames?gender=doggy").end(function(res) {
          expect(res.body.firstnames[0].gender).to.exist;
          return done();
        });
      });
    });
  });
});
