// Generated by CoffeeScript 1.7.1
var fastSimpleQuery, frequencyQuery, isUndefined, knex, limitQuery;

knex = require("knex").knex;

fastSimpleQuery = function(context) {
  return context.where(knex.raw("id in (select (random()*(select last_value from surnames_id_seq))::bigint from generate_series(1,120))"));
};

frequencyQuery = function(context, freq) {
  if (freq === "low") {
    return context.where("frequency", "<", 0.06);
  } else if (freq === "medium") {
    return context.where("frequency", ">=", 0.06).andWhere("frequency", "<", 1);
  } else if (freq === "high") {
    return context.where("frequency", ">=", 1);
  } else {
    return fastSimpleQuery(context);
  }
};

limitQuery = function(limit) {
  if ((limit <= 100) && (limit >= 1)) {
    return limit;
  } else {
    return 10;
  }
};

isUndefined = function(element, index, array) {
  return element === undefined;
};

module.exports.isUndefined = isUndefined;

module.exports.limitQuery = limitQuery;

module.exports.fast = fastSimpleQuery;

module.exports.frequencyQuery = frequencyQuery;
